services:
  - type: web
    name: flask-vue-app
    env: python
    buildCommand: |
      cd Frontend/mathtalk-vue
      npm install
      npm run build
      cd ../../
    startCommand: gunicorn app:app
    buildFilter:
      paths:
        - Frontend/mathtalk-vue/**
        - app.py
        - templates/**
        - static/**
        - requirements.txt
